[package]
name = "mx-contracts-rs-meta"
version = "0.0.0"
edition = "2021"
publish = false
authors = [ "you",]

[dependencies.mx-contracts-rs]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.43.5"
